### ISSUE TITLE
How to use it for Google Accounts with Advanced Protection

### ISSUE THREAD

**Issue by vorburger** [jamesread/prometheus-gmail-exporter#14]
It seems to be difficult to use this tool (or generally anything like it) for [Google Accounts with Advanced Protection](https://landing.google.com/advancedprotection/).

After sorted out unrelated issues like #10 et al, it will still fail due to _Access blocked: (...) is not approved by Advanced Protection_ with `Error 400: policy_enforced`.

The [Support Page that the Sign In error page links to in this case](https://support.google.com/accounts/answer/7539956#zippy=%2Ccan-i-still-use-sign-in-with-google%2Ccan-i-use-non-google-apps-services-or-apps-script-with-advanced-protection) doesn't explain exactly how to request and get approval for an app (=OAuth 2.0 Client ID) to be enabled for Google Accounts with Advanced Protection.

If I ever learn more about and find out how to do this, I'll document it here.

**Comment by jamesread** [comment]
Understood. Unfortunately I don't have a gmail/google account with Advanced Protection to test this against, but I welcome any fixes / patches that might be necessary.

**Comment by vorburger** [comment]
@jamesread I'm actually not even 100% sure if this does require any fixes / patches in code - or perhaps only... something in the OAuth 2.0 Client ID set-up, to submit it for some approval, or something. If I figure it out I'll raise a PR to document it in the README.

**Comment by jamesread** [comment]
I would be surprised if it needed a change in the OAuth flow to be honest, as that would be a pain for any app trying to integrate via OAuth.

**Comment by vorburger** [comment]
So apparently to use the Gmail API for Google Accounts with Advanced Protection one cannot use [an _OAuth consent screen_ that is only in _Publishing status = Testing_,](https://support.google.com/cloud/answer/10311615) but must _Publish the App_ and [then have it verified](https://support.google.com/cloud/answer/9110914).

**Comment by jamesread** [comment]
Ah, well, I'd say that's down to individual users of the project then - as there isn't going to be a publish "shared" OliveTin app registration for people to use.

**Comment by vorburger** [comment]
@jamesread Yeah, agreed; that makes sense. Maybe just some doc about it? Let's close this with #26.
